#!/bin/sh

pods=$(kubectl get po  | awk '{print $1}' | tr -d NAME)

num=$(echo $pods | wc -w)

mod=$(( $(( $RANDOM % $num )) + 1 ))

target=$(echo $pods | awk "{print \$$mod}")
echo "killing $target..."

kubectl delete po $target --force

synonyms[0]='destroyed'
synonyms[1]='annihilated'
synonyms[2]='obliterated'
synonyms[3]='slaughtered'
synonyms[4]='eliminated'
synonyms[5]='eradicated'
synonyms[6]='extinguished'
synonyms[7]='exterminated'
synonyms[8]='vaporized'
synonyms[9]='crushed'

syn_mod=$(( $RANDOM % 10 ))

echo "Hades has ${synonyms[${syn_mod}]} ${target}" >> /hades_activity.log
